### ISSUE TITLE
Keyboard input assumes qwerty layout

### ISSUE THREAD

**Issue by emoon** [sasq64/chipmachine#36] opened 2016-01-04 16:26 UTC
If one uses a non-qwerty layout set in Windows the app still assumes that it's always qwerty.

**Comment by sasq64** [comment] 2016-01-07 16:08
Seems to be caused by this;
https://github.com/glfw/glfw/issues/518

Will try to upgrade glfw for the next release.

**Comment by emoon** [comment] 2016-01-07 16:12
Sweet! Thanks.

**Comment by sasq64** [comment] 2016-05-02 09:29
Fixed in 1.3b

**Closed by sasq64** 2016-05-02 09:29 UTC

**Comment by emoon** [comment] 2016-05-02 09:32
Thanks :)
